name: Build and Deploy to Deploy Branch

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install and Build
        run: |
          npm install
          npm run build

      - name: Deploy to deploy branch
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git checkout deploy || git checkout -b deploy
          rm -rf *
          cp -R dist/* .
          git add .
          git commit -m "Deploy from main branch: ${{ github.sha }}"
          git push origin deploy --force
